### ISSUE TITLE
Error Can't load IA 32-bit .dll on a AMD 64-bit platform  io.humble.ferry.JNILibrary

### ISSUE THREAD

**Issue by jpalumbo1981** [artclarke/humble-video#109]
Hi budy, how are you?
i have a couple day trying to make work io-humble library, and i have to tell you, its make me crazy. i cant find a right way to do it.
Every time i try, i get the next error message.  

Honestly, i cant figure out the solution.  I'm working on a pc under windows 10.
Please, can you help me with this?

`public class ReordVideo {

    public static void record(String file, Rectangle screenbounds, int duration) {
        new Thread(() -> {
            try {
                final Robot robot = new Robot();
                
                final Muxer muxer = Muxer.make(file, null, "mpegts");
                final MuxerFormat format = muxer.getFormat();
                final Codec codec = Codec.findEncodingCodec(format.getDefaultVideoCodecId());
                Encoder encoder = Encoder.make(codec);
                encoder.setWidth(screenbounds.width);
                encoder.setHeight(screenbounds.height);
                final PixelFormat.Type pixelformat = PixelFormat.Type.PIX_FMT_YUV420P;
                encoder.setPixelFormat(pixelformat);
                encoder.setTimeBase(Rational.make(1, 10)); //framerate
                if (format.getFlag(MuxerFormat.Flag.RAW_PICTURE)) {
                    encoder.setFlag(Encoder.Flag.FLAG_GLOBAL_HEADER, true);
                }
                encoder.open(null, null);
                muxer.addNewStream(encoder);
                muxer.open(null, null);
                MediaPictureConverter converter = null;
                final MediaPicture picture = MediaPicture.make(
                        encoder.getWidth(),
                        encoder.getHeight(),
                        pixelformat);
                picture.setTimeBase(encoder.getTimeBase());
                final MediaPacket packet = MediaPacket.make();
                for (int i = 0; i < duration / encoder.getTimeBase().getDouble(); i++) {
                    final BufferedImage screen
                            = convertToType(robot.createScreenCapture(screenbounds),
                                    BufferedImage.TYPE_3BYTE_BGR);
                    if (converter == null) {
                        converter = MediaPictureConverterFactory.createConverter(screen, picture);
                    }
                    converter.toPicture(picture, screen, i);
                    do {
                        encoder.encode(packet, picture);
                        if (packet.isComplete()) {
                            muxer.write(packet, false);
                        }
                    } while (packet.isComplete());
                    Thread.sleep((long) (1000 * encoder.getTimeBase().getDouble()));
                    do {
                        encoder.encode(packet, null);
                        if (packet.isComplete()) {
                            muxer.write(packet, false);
                        }
                    } while (packet.isComplete());
                    muxer.close();
                }
            } catch (AWTException | InterruptedException | IOException ex) {
                Logger.getLogger(ReordVideo.class.getName()).log(Level.SEVERE, null, ex);
            }
       }).start();
    }
}`

Humble Version: Class: io.humble.video_native.Version; Specification Vendor: Humble Software; Specification Title: humble-video-arch-i686-w64-mingw32; Specification Version: 0.2.1; Implementation Vendor: Humble Software; Implementation Title: humble-video-arch-i686-w64-mingw32; Implementation Version: 0.2.1;
07:45:50.211 [Thread-44] DEBUG io.humble.ferry.JNILibrary - Failure: library load of library: humblevideo; url: C:\Users\JOSEAN~1\AppData\Local\Temp\humble8103148009760715820.dll; error: {}
java.lang.UnsatisfiedLinkError: C:\Users\JoseAntonio\AppData\Local\Temp\humble8103148009760715820.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.humble.ferry.JNILibrary.doJNILoad(JNILibrary.java:203)
	at io.humble.ferry.JNILibrary.unpackLibrary(JNILibrary.java:287)
	at io.humble.ferry.JNILibrary.loadFromClasspath(JNILibrary.java:189)
	at io.humble.ferry.JNILibrary.load(JNILibrary.java:168)
	at io.humble.ferry.JNILibrary.load(JNILibrary.java:149)
	at io.humble.ferry.FerryJNI.<clinit>(FerryJNI.java:16)
	at io.humble.ferry.Ferry.<clinit>(Ferry.java:24)
	at io.humble.video.VideoJNI.<clinit>(VideoJNI.java:19)
	at io.humble.video.Muxer.make(Muxer.java:139)
	at com.plogging.serengeti.ReordVideo.lambda$record$0(ReordVideo.java:39)
	at com.plogging.serengeti.ReordVideo$$Lambda$20/960707500.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Qt: Untested Windows version 6.3 detected!
Qt: Untested Windows version 6.3 detected!
07:46:10.435 [Thread-44] ERROR io.humble.video.Encoder - HumbleRuntimeError("Cannot add data to an encoder after you passed in null; encoder is flushing"): Cannot add data to an encoder after you passed in null; encoder is flushing (Encoder.cpp:258)
Exception in thread "Thread-44" java.lang.RuntimeException: Cannot add data to an encoder after you passed in null; encoder is flushing
	at io.humble.video.VideoJNI.Encoder_encode(Native Method)
	at io.humble.video.Encoder.encode(Encoder.java:248)
	at com.plogging.serengeti.ReordVideo.lambda$record$0(ReordVideo.java:70)
	at com.plogging.serengeti.ReordVideo$$Lambda$20/960707500.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cqjjjzr** [comment]
obviously, the library can't find the correct dll to load. don't know the solution, try ask art.

**Comment by jpalumbo1981** [comment]
8:48:29 a. m. - j.cabrera@pacific-logging.com: i'm working in a maven project (java)  using just official repo

**Comment by jpalumbo1981** [comment]
i'm working in a maven project (java)  using just official repo

**Comment by osenbghe** [comment]
Could be a JavaVM Issue.
Java Version 1.8.**131** fires this error on 64Bit
Java Version 1.8.**92** (under 100 on the last digit) runs fine without this type of error on 64Bit

**Comment by huhlig** [comment]
Encountering the same problem and I think I've identified why.

extract
13:16:47.729 [main] DEBUG io.humble.ferry.JNILibrary - Failure: library load of library: humblevideo; url: C:\Users\huhlig\AppData\Local\Temp\humble226315281306700012.dll; error: {}
java.lang.UnsatisfiedLinkError: C:\Users\huhlig\AppData\Local\Temp\humble226315281306700012.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.humble.ferry.JNILibrary.doJNILoad(JNILibrary.java:203)
	at io.humble.ferry.JNILibrary.unpackLibrary(JNILibrary.java:287)
	at io.humble.ferry.JNILibrary.loadFromClasspath(JNILibrary.java:189)
	at io.humble.ferry.JNILibrary.load(JNILibrary.java:168)
	at io.humble.ferry.JNILibrary.load(JNILibrary.java:149)
	at io.humble.ferry.FerryJNI.<clinit>(FerryJNI.java:16)
	at io.humble.ferry.Ferry.<clinit>(Ferry.java:24)
	at io.humble.video.VideoJNI.<clinit>(VideoJNI.java:19)
	at io.humble.video.AudioChannel$Layout.<clinit>(AudioChannel.java:297)
	at com.ibm.dxf.contenthub.extension.videoimporter.helpers.AudioVideoStreamer$Builder.<clinit>(AudioVideoStreamer.java:82)
	at com.ibm.dxf.contenthub.extension.videoimporter.helpers.AudioVideoStreamer.create(AudioVideoStreamer.java:77)
	at com.ibm.dxf.contenthub.extension.videoimporter.helpers.AudioVideoStreamerTest.testExtract(AudioVideoStreamerTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Archive:  humble-video-arch-x86_64-w64-mingw32-0.2.1.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
     1352  01-01-15 22:52   META-INF/MANIFEST.MF
      816  01-03-15 08:38   META-INF/HUMBLESO.SF
     1156  01-03-15 08:38   META-INF/HUMBLESO.DSA
        0  01-02-15 06:40   META-INF/
        0  01-02-15 06:40   META-INF/maven/
        0  01-02-15 06:40   META-INF/maven/io.humble/
        0  01-02-15 06:40   META-INF/maven/io.humble/humble-video-arch-x86_64-w64-mingw32/
     2323  01-01-15 21:37   META-INF/maven/io.humble/humble-video-arch-x86_64-w64-mingw32/pom.xml
      130  01-02-15 06:40   META-INF/maven/io.humble/humble-video-arch-x86_64-w64-mingw32/pom.properties
      239  01-02-15 06:40   META-INF/INDEX.LIST
        0  01-02-15 06:40   io/
        0  01-02-15 06:40   io/humble/
        0  01-02-15 06:40   io/humble/video_native/
     1496  01-02-15 06:40   io/humble/video_native/Version.class
119976813  01-02-15 06:40   libhumblevideo-0.dll
 --------                   -------
119984325                   15 files

**Comment by huhlig** [comment]
Experiencing same issue with Java(TM) SE Runtime Environment (build 1.8.0_131-b11) JDK

**Comment by java-sandbox** [comment]
I've solved this error by excluding arch artifacts for other platforms, so snippet from my pom.xml:
<dependency>
            <groupId>io.humble</groupId>
            <artifactId>humble-video-all</artifactId>
            <version>0.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>io.humble</groupId>
                    <artifactId>humble-video-arch-i686-apple-darwin12</artifactId>
                </exclusion>
                ... <artifactId>humble-video-arch-x86_64-apple-darwin12</artifactId>
                ... <artifactId>humble-video-arch-i686-pc-linux-gnu6</artifactId>
                ... <artifactId>humble-video-arch-x86_64-pc-linux-gnu6</artifactId>
                ... <artifactId>humble-video-arch-i686-w64-mingw32</artifactId>
            </exclusions>

**Comment by huhlig** [comment]
That's the same temporary work around I found.

Hans W. Uhlig - huhlig@gmail.com
PGP Key: F509CF9D892BDBE8
PGP Fingerprint: 74AF EDD7 7427 3288 45AB 6FCB F509 CF9D 892B DBE8

**Comment by SeunMatt** [comment]
This is for anybody coming here later. This worked for me on a Windows 10 64-bit system:

```java
<dependency>
            <groupId>io.humble</groupId>
            <artifactId>humble-video-all</artifactId>
            <version>0.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>io.humble</groupId>
                    <artifactId>humble-video-arch-x86_64-apple-darwin12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.humble</groupId>
                    <artifactId>humble-video-arch-i686-pc-linux-gnu6</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.humble</groupId>
                    <artifactId>humble-video-arch-x86_64-pc-linux-gnu6</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.humble</groupId>
                    <artifactId>humble-video-arch-i686-apple-darwin12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.humble</groupId>
                    <artifactId>humble-video-arch-i686-w64-mingw32</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
