### ISSUE TITLE
can not run demo ContainerSegmenter 

### ISSUE THREAD

**Issue by lixuwei** [artclarke/humble-video#51]
I copy sources run : 

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not write packet to muxer : Invalid data found when processing input (-1094995529)
        at io.humble.video.VideoJNI.Muxer_write(Native Method)
        at io.humble.video.Muxer.write(Muxer.java:259)
        at com.lee.study.humble.ContainerSegmenter.segmentFile(ContainerSegmenter.java:104)
        at com.lee.study.humble.ContainerSegmenter.main(ContainerSegmenter.java:199)
        ... 6 more

**Comment by artclarke** [comment]
Can you post the arguments you gave to the demo, along with a link to the source media somewhere accessible online and I will take a look?

**Comment by lixuwei** [comment]
I uploaded my project to github, which contains the MP4 files
https://github.com/lixuwei/humble-hello  
thanks artclarke

**Comment by isatimur** [comment]
Hi Art,
I have similar problem that videos u have packed in demos are working, but mine not really. I have checked that metadata is different. Can it be the reason of problem and is there a way how to solve it.
<code>
this is meta of mine video 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'bbb.mp4':									
  Metadata:									
    major_brand     : isom									
    minor_version   : 512									
    compatible_brands: isomiso2avc1mp41									
    encoder         : Lavf56.36.100									
  Duration: 00:09:56.54, start: 0.021333, bitrate: 612 kb/s									
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1280:1281 DAR 16:9], 478 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)									
    Metadata:									
      handler_name    : VideoHandler									
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)									
    Metadata:									
      handler_name    : SoundHandler									
</code>

and this is yours
<code>
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'ucl_h264_aac.mp4':								
  Metadata:								
    major_brand     : mp42								
    minor_version   : 0								
    compatible_brands: isomavc1mp42								
    creation_time   : 2007-09-27 15:01:39								
  Duration: 00:00:15.91, start: 0.000000, bitrate: 383 kb/s								
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 33 kb/s (default)								
    Metadata:								
      creation_time   : 2007-09-27 15:01:39								
      handler_name    : (C) 2007 Google Inc. v06.24.2007.								
    Stream #0:1(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 480x360 [SAR 1:1 DAR 4:3], 347 kb/s, 30 fps, 30 tbr, 30k tbn, 60k tbc (default)								
    Metadata:								
      creation_time   : 2007-09-27 15:01:39								
      handler_name    : (C) 2007 Google Inc. v06.24.2007.								
</code>
