### ISSUE TITLE
ChannelLayout always CH_LAYOUT_UNKNOWN for wav-files.

### ISSUE THREAD

**Issue by tly000** [artclarke/humble-video#57]
Im trying to resample audio files for a mediaplayer and every mp3-file is working fine but any wav-file has channel layout CH_LAYOUT_UNKNOWN. 

Here is the code that i use to create the MediaAudio sample:
```java
//t saves a source url and a streamid of a track.
demuxer.open(t.getSource(), null, true, true, null, null);
decoder = demuxer.getStream(t.getStreamID()).getDecoder();
streamID = t.getStreamID();
decoder.open(null, null);
samples = MediaAudio.make(
	decoder.getFrameSize(),
	decoder.getSampleRate(), 
	decoder.getChannels(),
	decoder.getChannelLayout(),
	decoder.getSampleFormat());
	System.out.println("sampleFormat is "+samples);
	System.out.println("channelLayout is "+decoder.getChannelLayout());
```

Sample output for a wav-file:

```
sampleFormat is io.humble.video.MediaAudio@4068448[sample rate:44100;channels:2;format:SAMPLE_FMT_S16;time stamp:-9223372036854775808;complete:false;num samples:576;key:true;time base:1/44100;planes:1;plane size[0]:2304;]
channelLayout is CH_LAYOUT_UNKNOWN
```

Needless to say, I cant create a MediaAudioResampler without knowing the layout. I used Xuggler before and used the IMediaViewer to play the files and wav files worked normally.

**Comment by borjaevo** [comment]
I have same problem with MP4 audio which is PCM S16 LE (swot) MONO

**Comment by borjaevo** [comment]
I resolved this forcing audio decoder to use MONO channel Layout.
But i have other problems: Frame size is bad calculated. I have to count audio packets before playing and calculate frame size manually. It always set frame size to 576 and in my case was 880, so audio quality was very bad.

**Comment by smikesmike** [comment]
I still run into the same problem. I've used successfully xuggle for many years without problems and try to migrate now to humble. I want to process PCM coded audio files but I get always the error that the channel layout is unknown.

The simplest test to reproduce is to run DecodeAndPlayAudio.java with a wav file.

Is there a workaround for this available?

**Comment by hemeda3** [comment]
I have same issue when I use DecodeAndPlayAudio.java with "wav" file audio
`Exception in thread "main" java.lang.IllegalArgumentException: channel layout must be known
	at io.humble.video.javaxsound.StereoS16AudioConverter.<init>(StereoS16AudioConverter.java:40)
	at io.humble.video.javaxsound.MediaAudioConverterFactory.createConverter(MediaAudioConverterFactory.java:49)
	at io.humble.video.javaxsound.MediaAudioConverterFactory.createConverter(MediaAudioConverterFactory.java:25)`
